train:
  base_model: "yolov8n.pt"
  epochs: 15
  imgsz: 640
  patience: 10
  batch: 8
  device: 'mps'     # '0' for GPU, 'cpu', 'mps' for Mac

quantize:
  format: "tflite" # Target format for conversion
